version: "3.9"
services:
  mysql8:
    container_name: mysql8
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: msvc_usuarios     
      MYSQL_ROOT_PASSWORD: sasa
    volumes:
      - data-mysql:/var/lib/mysql
    restart: always
    networks:
      - spring
  postgres14:
    container_name: postgres14
    image: postgres:14-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: msvc_cursos     
      POSTGRES_PASSWORD: sasa
    volumes:
      - data-postgres:/var/lib/postgres/data
    restart: always
    networks:
      - spring
      
  msvc-usuarios:
    container_name: msvc-usuarios
    image: delicatessen23/usuarios:latest   
    #image: usuarios:latest
#    build: 
#      context: ./
#      dockerfile: ./msvc-usuarios/Dockerfile
    ports: 
      - "8001:8001"
    #env_file: ./msvc-usuarios/.env
    environment:
      PORT: 8001
      DB_HOST: mysql8:3306
      DB_DATABASE: msvc_usuarios
      DB_USERNAME: root
      DB_PWD: sasa
      CURSOS_URL: msvc-cursos:8002
    networks:
      - spring
    depends_on: 
      - mysql8
    restart: always
          
  msvc-cursos:
    container_name: msvc-cursos
    image: delicatessen23/cursos:latest
    #image: cursos:latest
#    build: 
#      context: ./
#      dockerfile: ./msvc-cursos/Dockerfile
    ports: 
      - "8002:8002"
    #env_file: ./msvc-cursos/.env
    environment:
      PORT: 8002
      DB_HOST: postgres14:5432
      DB_DATABASE: msvc_cursos
      DB_USERNAME: postgres
      DB_PWD: sasa
      USUARIOS_URL: msvc-usuarios:8001
    networks:
      - spring
    depends_on: 
      - postgres14
      - msvc-usuarios
    restart: always
    
volumes:
  data-mysql:
    name: data-mysql
  data-postgres:
    name: data-postgres
  
networks:
  spring:
    name: spring