version: "3.9"
services:
  mysql8:
    container_name: mysql8
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: msvc_usuarios     
      MYSQL_ROOT_PASSWORD: sasa
    volumes:
      - data-mysql:/var/lib/mysql
    restart: always
    networks:
      - spring
      
  msvc-usuarios:
    container_name: msvc-usuarios
    image: delicatessen23/usuarios:latest   
    #image: usuarios:latest
#    build: 
#      context: ./
#      dockerfile: ./msvc-usuarios/Dockerfile
    ports: 
      - "8001:8001"
    #env_file: ./msvc-usuarios/.env
    environment:
      PORT: 8001
      DB_HOST: mysql8:3306
      DB_DATABASE: msvc_usuarios
      DB_USERNAME: root
      DB_PWD: sasa
      CURSOS_URL: ec2-54-174-255-127.compute-1.amazonaws.com:8002
    networks:
      - spring
    depends_on: 
      - mysql8
    restart: always

volumes:
  data-mysql:
    name: data-mysql
  
networks:
  spring:
    name: spring